service: ping-my-telegram

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: dev
  profile: janMatzek
  architecture: x86_64
  timeout: 30
  memorySize: 1024

functions:
  readRoot:
    handler: handler.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /contact_form
          method: post

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 2
  serverless-offline:
    noTimeout: true
  pythonRequirements:
    useDownloadCache: false
    layer: true
    slim: true
    usePoetry: false
    dockerizePip: true

package:
  patterns:
    - "!__pycache__"
    - "!.serverless"
    - "!venv"
    - "!.gitignore"
    - "!env"
    - "!.env"
    - "telegram_messenger_frog.py"
